"""Stage 5.2 subject-aware spatial localization."""

from .rt_detr_localizer import DEFAULT_MODEL_ID, RTDetrLocalizer
from .full_dev import (
    FrameIdentityError,
    ShardStateError,
    ShardStatus,
    canonical_sha,
    file_sha256,
    load_shard_records,
    merge_and_verify,
    pick_even,
    shard_is_complete,
    shard_paths,
    write_shard,
)
from .subject_to_crop import (
    STATUS_CONTAINS_SUBJECT,
    STATUS_DEGRADED_MAX_CROP,
    DiagnosticCrop,
    subject_centered_crop,
)
from .subject_localization import (
    FALLBACK_REASONS,
    REASON_BOX_TOO_LARGE,
    REASON_BOX_TOO_SMALL,
    REASON_FULL_FRAME_LIKE,
    REASON_INVALID_GEOMETRY,
    REASON_LOW_CONFIDENCE,
    REASON_MODEL_ERROR,
    REASON_MULTI_SUBJECT_AMBIGUOUS,
    REASON_NO_DETECTION,
    STATUS_CENTER_CROP_FALLBACK,
    STATUS_PRIMARY,
    SubjectCandidate,
    SubjectDecision,
    SubjectPolicyConfig,
    candidate_is_valid,
    clamp_box,
    decision_to_record,
    detection_iou,
    select_primary_subject,
)
from .visualization import render_decision_frame, save_decision_image

__all__ = [
    "FrameIdentityError",
    "ShardStateError",
    "ShardStatus",
    "DEFAULT_MODEL_ID",
    "FALLBACK_REASONS",
    "RTDetrLocalizer",
    "REASON_BOX_TOO_LARGE",
    "REASON_BOX_TOO_SMALL",
    "REASON_FULL_FRAME_LIKE",
    "REASON_INVALID_GEOMETRY",
    "REASON_LOW_CONFIDENCE",
    "REASON_MODEL_ERROR",
    "REASON_MULTI_SUBJECT_AMBIGUOUS",
    "REASON_NO_DETECTION",
    "STATUS_CENTER_CROP_FALLBACK",
    "STATUS_PRIMARY",
    "SubjectCandidate",
    "SubjectDecision",
    "SubjectPolicyConfig",
    "DiagnosticCrop",
    "STATUS_CONTAINS_SUBJECT",
    "STATUS_DEGRADED_MAX_CROP",
    "candidate_is_valid",
    "canonical_sha",
    "clamp_box",
    "decision_to_record",
    "detection_iou",
    "file_sha256",
    "load_shard_records",
    "merge_and_verify",
    "pick_even",
    "render_decision_frame",
    "save_decision_image",
    "select_primary_subject",
    "shard_is_complete",
    "shard_paths",
    "subject_centered_crop",
    "write_shard",
]
